-- Marketplace database schema
-- Run once in the e_commerce_db database.

CREATE TABLE IF NOT EXISTS users (
                                     id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                     username VARCHAR(50) NOT NULL UNIQUE,
                                     password_hash VARCHAR(255) NOT NULL,
                                     full_name VARCHAR(100) NOT NULL,
                                     role VARCHAR(20) NOT NULL DEFAULT 'CUSTOMER',

                                     CONSTRAINT users_role_check
                                         CHECK (role IN ('ADMIN', 'SELLER', 'CUSTOMER'))
);

CREATE TABLE IF NOT EXISTS categories (
                                          id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                          name VARCHAR(100) NOT NULL UNIQUE
);

CREATE TABLE IF NOT EXISTS products (
                                        id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                        seller_id BIGINT NOT NULL,
                                        category_id BIGINT NOT NULL,
                                        name VARCHAR(150) NOT NULL,
                                        price NUMERIC(12, 2) NOT NULL,
                                        stock INTEGER NOT NULL DEFAULT 0,
                                        is_active BOOLEAN NOT NULL DEFAULT TRUE,

                                        CONSTRAINT products_price_check
                                            CHECK (price > 0),

                                        CONSTRAINT products_stock_check
                                            CHECK (stock >= 0),

                                        CONSTRAINT products_seller_fk
                                            FOREIGN KEY (seller_id)
                                                REFERENCES users(id)
                                                ON DELETE RESTRICT,

                                        CONSTRAINT products_category_fk
                                            FOREIGN KEY (category_id)
                                                REFERENCES categories(id)
                                                ON DELETE RESTRICT
);

CREATE TABLE IF NOT EXISTS cart_items (
                                          user_id BIGINT NOT NULL,
                                          product_id BIGINT NOT NULL,
                                          quantity INTEGER NOT NULL,

                                          CONSTRAINT cart_items_pk
                                              PRIMARY KEY (user_id, product_id),

                                          CONSTRAINT cart_quantity_check
                                              CHECK (quantity > 0),

                                          CONSTRAINT cart_user_fk
                                              FOREIGN KEY (user_id)
                                                  REFERENCES users(id)
                                                  ON DELETE CASCADE,

                                          CONSTRAINT cart_product_fk
                                              FOREIGN KEY (product_id)
                                                  REFERENCES products(id)
                                                  ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS wishlist_items (
                                              user_id BIGINT NOT NULL,
                                              product_id BIGINT NOT NULL,

                                              CONSTRAINT wishlist_items_pk
                                                  PRIMARY KEY (user_id, product_id),

                                              CONSTRAINT wishlist_user_fk
                                                  FOREIGN KEY (user_id)
                                                      REFERENCES users(id)
                                                      ON DELETE CASCADE,

                                              CONSTRAINT wishlist_product_fk
                                                  FOREIGN KEY (product_id)
                                                      REFERENCES products(id)
                                                      ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS orders (
                                      id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                      customer_id BIGINT NOT NULL,
                                      status VARCHAR(30) NOT NULL DEFAULT 'PENDING',
                                      total_amount NUMERIC(12, 2) NOT NULL,
                                      created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,

                                      CONSTRAINT orders_status_check
                                          CHECK (status IN ('PENDING', 'PAID', 'CANCELLED', 'COMPLETED')),

                                      CONSTRAINT orders_total_check
                                          CHECK (total_amount >= 0),

                                      CONSTRAINT orders_customer_fk
                                          FOREIGN KEY (customer_id)
                                              REFERENCES users(id)
                                              ON DELETE RESTRICT
);

CREATE TABLE IF NOT EXISTS order_items (
                                           id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                           order_id BIGINT NOT NULL,
                                           product_id BIGINT NOT NULL,
                                           quantity INTEGER NOT NULL,
                                           unit_price NUMERIC(12, 2) NOT NULL,

                                           CONSTRAINT order_quantity_check
                                               CHECK (quantity > 0),

                                           CONSTRAINT order_price_check
                                               CHECK (unit_price > 0),

                                           CONSTRAINT order_items_unique_product
                                               UNIQUE (order_id, product_id),

                                           CONSTRAINT order_items_order_fk
                                               FOREIGN KEY (order_id)
                                                   REFERENCES orders(id)
                                                   ON DELETE CASCADE,

                                           CONSTRAINT order_items_product_fk
                                               FOREIGN KEY (product_id)
                                                   REFERENCES products(id)
                                                   ON DELETE RESTRICT
);

CREATE TABLE IF NOT EXISTS payments (
                                        id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                        order_id BIGINT NOT NULL,
                                        amount NUMERIC(12, 2) NOT NULL,
                                        method VARCHAR(30) NOT NULL,
                                        status VARCHAR(30) NOT NULL,
                                        created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,

                                        CONSTRAINT payment_amount_check
                                            CHECK (amount > 0),

                                        CONSTRAINT payment_method_check
                                            CHECK (method IN ('CASH', 'CARD', 'QR')),

    -- The Java application saves SUCCESS or FAILED.
                                        CONSTRAINT payment_status_check
                                            CHECK (status IN ('SUCCESS', 'FAILED')),

                                        CONSTRAINT payments_order_fk
                                            FOREIGN KEY (order_id)
                                                REFERENCES orders(id)
                                                ON DELETE RESTRICT
);

CREATE TABLE IF NOT EXISTS reviews (
                                       id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                       user_id BIGINT NOT NULL,
                                       product_id BIGINT NOT NULL,
                                       rating INTEGER NOT NULL,
                                       comment TEXT NOT NULL DEFAULT '',
                                       created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,

                                       CONSTRAINT review_rating_check
                                           CHECK (rating BETWEEN 1 AND 5),

                                       CONSTRAINT reviews_user_fk
                                           FOREIGN KEY (user_id)
                                               REFERENCES users(id)
                                               ON DELETE CASCADE,

                                       CONSTRAINT reviews_product_fk
                                           FOREIGN KEY (product_id)
                                               REFERENCES products(id)
                                               ON DELETE CASCADE,

                                       CONSTRAINT reviews_unique_user_product
                                           UNIQUE (user_id, product_id)
);

-- Indexes used for common searches and reports.
CREATE INDEX IF NOT EXISTS idx_products_seller
    ON products(seller_id);

CREATE INDEX IF NOT EXISTS idx_products_category_active
    ON products(category_id, is_active);

CREATE INDEX IF NOT EXISTS idx_orders_customer_created
    ON orders(customer_id, created_at DESC);

CREATE INDEX IF NOT EXISTS idx_order_items_product
    ON order_items(product_id);

CREATE INDEX IF NOT EXISTS idx_payments_order
    ON payments(order_id);

CREATE INDEX IF NOT EXISTS idx_reviews_product_created
    ON reviews(product_id, created_at DESC);

-- Starter categories.
INSERT INTO categories (name)
VALUES
    ('Electronics'),
    ('Clothing'),
    ('Drinks'),
    ('Books')
ON CONFLICT (name) DO NOTHING;